version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresForDb
    environment:
      POSTGRES_DB: piscineds
      POSTGRES_USER: jaehwkim
      POSTGRES_PASSWORD: "mysecretpassword"
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .:/csv_data

  # --- PgAdmin 서비스 정의 시작 ---
  pgadmin:
    image: dpage/pgadmin4 
    container_name: pgadmin_for_piscine 
    environment:
      
      PGADMIN_DEFAULT_EMAIL: jaehwkim@naver.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "5050:80" 
    volumes:
      - pgadmin_data:/var/lib/pgadmin 
    depends_on:
      - db 
  # --- PgAdmin 서비스 정의 끝 ---

volumes:
  postgres_data:
  # --- PgAdmin 볼륨 정의 시작 ---
  pgadmin_data:
  # --- PgAdmin 볼륨 정의 끝 ---